### ISSUE TITLE
Current? What happened to Stable? (v6.0.0)

### ISSUE THREAD

**Issue by coreybutler** [coreybutler/nodedistro#24]
REPOSTED FROM https://github.com/coreybutler/nvm-windows/issues/164 (@vellotis)

Node has changed its version labeling. v6.0.0 is in https://raw.githubusercontent.com/coreybutler/nodedistro/master/nodeversions.json but only under `all` json key. It is not under `stable` or `unstable` json keys. This means it is installable, but it is not showed as an available version.

Referenced from https://nodejs.org/en/blog/release/v6.0.0/

> ### Current? What happened to Stable?
> You may have noticed that the v6 release uses the label `Current` instead of Stable. This name change has been made in order to better differentiate the Long Term Support releases from the `current` active development branches. We will be using the `Current` label from here-on instead of Stable.

### Expected Behavior

Following is just a suggestion. As `nodeversions.json` is handled by you, @coreybutler, maybe you want to list it as stable instead of putting it in `all`?

```bash
> nvm list available

Showing the 15 latest available releases.

   CURRENT: v6.0.0

      STABLE   |    UNSTABLE
   ---------------------------
      v5.10.1  |     v5.11.0
      v5.10.0  |      v5.9.1
       v5.8.0  |      v5.9.0
       v4.4.3  |      v5.7.1
       v4.4.2  |      v5.7.0
       v4.4.1  |    v0.11.16
       v4.4.0  |    v0.11.15
       v4.3.2  |    v0.11.14
       v4.3.1  |    v0.11.13
       v4.3.0  |    v0.11.12
       v4.2.6  |    v0.11.11
       v4.2.5  |    v0.11.10
       v4.2.4  |     v0.11.9
       v4.2.3  |     v0.11.8
       v4.2.2  |     v0.11.7
```

### Actual Behavior

```bash
> nvm list available

Showing the 15 latest available releases.

      STABLE   |    UNSTABLE
   ---------------------------
      v5.10.1  |     v5.11.0
      v5.10.0  |      v5.9.1
       v5.8.0  |      v5.9.0
       v4.4.3  |      v5.7.1
       v4.4.2  |      v5.7.0
       v4.4.1  |    v0.11.16
       v4.4.0  |    v0.11.15
       v4.3.2  |    v0.11.14
       v4.3.1  |    v0.11.13
       v4.3.0  |    v0.11.12
       v4.2.6  |    v0.11.11
       v4.2.5  |    v0.11.10
       v4.2.4  |     v0.11.9
       v4.2.3  |     v0.11.8
       v4.2.2  |     v0.11.7
```

**Comment by coreybutler** [comment]
Fixed via dbb2e0aabdcc124d802902a466494d12a49b3918.

**Comment by vellotis** [comment]
Regards @coreybutler !

**Comment by coreybutler** [comment]
@vellotis FYI - I just merged a PR that to use the new release feed from Node, so this repository will go away over time. These kinds of issues shouldn't happen again!

**Comment by vellotis** [comment]
@coreybutler The pleasure's all mine!

2016-05-05 16:42 GMT+03:00 Corey Butler <notifications@github.com>:

**Comment by cloned2k16** [comment]
nvm list available .. still doesn't show any 6.x.x version 

actually mine doesn't show v4.2.2 either ...

**Comment by vellotis** [comment]
Seems that [b82822](https://github.com/coreybutler/nodedistro/commit/b82822c511c9acc6e50ec7739f9063ae2de03fb7#diff-143c4cd8a9b2993fa9e346cbfe02494b) broke it.

**Comment by cloned2k16** [comment]
I have just had a look at the source code,
  and turns out that the list get parsed from ..

[node.go].GetAvailable()
text := web.GetRemoteTextFile("https://nodejs.org/download/release/index.json")
... ... ..
return all, lts, stable, npm

which then returns to
[nvm.go]
where ...

    _, lts, stable, _ := node.GetAvailable()

    releases := 15
    fmt.Println("\nShowing the "+strconv.Itoa(releases)+" latest available releases.\n")

    fmt.Println("        LTS    |     STABLE   ")
    fmt.Println("   ---------------------------")

**Comment by cloned2k16** [comment]
the JSON file is correct 
 you can check it here ... http://cloned2k16.github.io/jsNVM/
